services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 3000:8080
    environment:
      - 'OLLAMA_BASE_URL=https://example-id.ngrok-free.app'
      - 'WEBUI_SECRET_KEY='
    restart: unless-stopped

volumes:
  open-webui: {}
